import "../js/is-autorization";
import $ from "jquery";
import "slick-carousel";
import "slick-carousel/slick/slick.scss";
import "../scss/main.scss";
import "./page.scss";
import "../js/indexadmin";
$(".slider__bottom--center").slick();
import "../jsForChart/addToChart";
import "../partials/footer";
